version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: ./api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASSWORD
      JWT_SECRET: $JWT_SECRET
      REFRESH_TOKEN_SECRET: $REFRESH_TOKEN_SECRET
      ACCESS_TOKEN_EXPIRES: $ACCESS_TOKEN_EXPIRES
      REFRESH_TOKEN_EXPIRES: $REFRESH_TOKEN_EXPIRES
      NODE_ENV: production
    depends_on:
      - postgres
    restart: unless-stopped

  vite-app:
    build: ./vite-app
    depends_on:
      - api
    ports:
      - "443:5173"
    restart: unless-stopped

volumes:
  db_data:
