version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Dzu%3IjGW831
      POSTGRES_DB: foodflow
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: oqP5@7X1X1&2
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
